public class Main {
    public static void main(String[] args) {
        byte first = 27;
        int second = 247;
        short third = 5000;
        long fourth = 123456789;
        float fifth =3.14f;
        double sixth = 2.99875287903;
        System.out.println("Значение переменной" + "first" + "с типом" +"byte" + "равно"+first);
        System.out.println("Значение переменной" + "second" + "с типом" +"int" + "равно"+second);
        System.out.println("Значение переменной" + "third" + "с типом" +"short" + "равно"+third);
        System.out.println("Значение переменной" + "fourth" + "с типом" +"long" + "равно"+fourth);
        System.out.println("Значение переменной" + "fifth" + "с типом" +"float" + "равно"+fifth);
        System.out.println("Значение переменной" + "sixth" + "с типом" +"double" + "равно"+sixth);
        float denmarkKrona=27.12f;
        long seconds= 987678965549L;
        double dollars=2.786f;
        int sticks=569;
        int temperature = -159;
        short glasses=27897;
        byte nuts=67;
        int lClass = 23;
        int aClass = 27;
        int eClass = 30;
        int paper = 480;
        int forEachStudent = paper/(lClass+aClass+eClass);
        System.out.println("На каждого ученика расчитано"+ forEachStudent +"листов бумаги");
        int workSpeedFor2Minutes = 16;
        int workSpeedFor1Minute= workSpeedFor2Minutes/2;
        int workSpeedFor20minutes = workSpeedFor1Minute*20;
        int workSpeedFor24Hours=workSpeedFor1Minute*1440;
        int workSpeedFor3Days = workSpeedFor24Hours*3;
        int workSpeedFor1Month = workSpeedFor24Hours*31;
        System.out.println("За"+"20 минут"+"машина произвела"+workSpeedFor20minutes+"штук бутылок");
        System.out.println("За"+"сутки"+"машина произвела"+workSpeedFor24Hours+"штук бутылок");
        System.out.println("За"+"3 дня"+"машина произвела"+workSpeedFor3Days+"штук бутылок");
        System.out.println("За"+"месяц"+"машина произвела"+workSpeedFor1Month+"штук бутылок");
        byte paint=120;
        byte whitePaintFor1Room=2;
        byte brownPainFor1Room=4;
        int needPaintFor1Room= whitePaintFor1Room+brownPainFor1Room;
        int howManyRoom= paint / needPaintFor1Room;
        byte howManyWhitePaint= (byte) (whitePaintFor1Room*howManyRoom);
        byte howManyBrownPaint=(byte) (brownPainFor1Room*howManyRoom);
        System.out.println("В школе , где "+ howManyRoom + "классов, нужно "+howManyWhitePaint+"банок белой краски и"+howManyBrownPaint+"банок коричневой краски");
        byte bananaMass=80;
        byte milkMass=105;
        byte iceCreamMass=100;
        byte eggMass=70;
        short bananasForReceipt= (short) (bananaMass*5);
        short milkForReceipt= (short) (milkMass*2);
        short iceCreamForReceipt= (short) (iceCreamMass*2);
        short eggForReceipt=(short) (eggMass*4);
        short massOfBreakfast= (short) (bananasForReceipt+milkForReceipt+iceCreamForReceipt+eggForReceipt);
        System.out.println(massOfBreakfast);
        float massInKilo=massOfBreakfast/1000F;
        System.out.println(massInKilo);
        short needToLoseMassInKilo=7;
        short needToLOseMassInGram= (short) (needToLoseMassInKilo*1000);
        short minimumLoseMassInDay=250;
        short maximumLOseMass=500;
        short dayIfLoseMinimumMass=(short)(needToLOseMassInGram/minimumLoseMassInDay);
        System.out.println(dayIfLoseMinimumMass);
        short dayIfLoseMaximumMass=(short) (needToLOseMassInGram/maximumLOseMass);
        System.out.println(dayIfLoseMaximumMass);
        short dayOnOverage=(short) ((dayIfLoseMaximumMass+dayIfLoseMinimumMass)/2);
        System.out.println(dayOnOverage);
        int mashaSalaryNow=67760;
        int percentOfSalary10Masha=mashaSalaryNow/10;
        int mashaSalaryAfterUp= mashaSalaryNow+percentOfSalary10Masha;
        int annualIncomeMashaNow=mashaSalaryNow*12;
        int annualIncomeMashaAfterUp=mashaSalaryAfterUp*12;
        int denisSalaryNow=83690;
        int annualIncomeDenisNow=denisSalaryNow*12;
        int percentOfSalary10Denis=denisSalaryNow/10;
        int denisSalaryAfterUp= denisSalaryNow+percentOfSalary10Denis;
        int annualIncomeAfterUpDenis= denisSalaryAfterUp*12;
        int kristinaSalaryNow=76230;
        int percentOfSalary10Kristina=kristinaSalaryNow/10;
        int kristinaSalaryAfterUp= kristinaSalaryNow+percentOfSalary10Kristina;
        int annulIncomeKristinaNow=kristinaSalaryNow*12;
        int annualIncomeKristinaAfterUp= kristinaSalaryAfterUp*12;
        int differenceAnnualIncomeMasha=annualIncomeMashaAfterUp-annualIncomeMashaNow;
        int differenceAnnualIncomeDenis=annualIncomeAfterUpDenis-annualIncomeDenisNow;
        int differenceAnnualIncomeKristina=annualIncomeKristinaAfterUp-annulIncomeKristinaNow;
        System.out.println("Маша теперь получает"+annualIncomeMashaAfterUp+"рублей. Годовой доход вырос на"+differenceAnnualIncomeMasha+"рублей");
        System.out.println("Денис теперь получает"+ annualIncomeAfterUpDenis+"рублей. Годовой доход вырос на"+differenceAnnualIncomeDenis+"рублей");
        System.out.println("Кристина теперь получает"+annualIncomeKristinaAfterUp+"рублей. Годовой доход вырос на"+differenceAnnualIncomeKristina+"рублей");


    }
}